.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OTPR" "1" "January 2014" "" ""
.
.SH "NAME"
\fBotpr\fR \- Long passwords from short pins\.
.
.SH "SYNOPSIS"
\fBotpr\fR \fIoptions\fR
.
.br
\fBotpr\fR \fB\-\-create\fR
.
.br
\fBotpr\fR \fB\-\-read\fR
.
.br
\fBotpr\fR \fB\-\-update\fR
.
.br
\fBotpr\fR \fB\-\-delete\fR
.
.br
.
.SH "DESCRIPTION"
\fBotpr\fR maintains short pins for long passwords\.
.
.SH "OPTIONS"
.
.TP
\fB\-c\fR, \fB\-\-create\fR
Create blah blah blah\.
.
.SH "EXAMPLES"
.
.SH "FILES"
\fB~/\.config/otpr/config\.json\fR
.
.SH "ENVIROMENT"
.
.SH "BUGS"
.
.SH "LICENSE"
.
.SH "AUTHOR"
.
.SH "COPYRIGHT"
.
.SH "SEE ALSO"

